-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

vim.api.nvim_set_hl(0, "Visual", { fg = "#ffffff", bg = "#6a8075" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#4e3630" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#243135" })
vim.api.nvim_set_hl(0, "DashboardFooter", { fg = "#81b29a" })
vim.api.nvim_set_hl(0, "DashboardHeader", { fg = "#c6825b" })
vim.api.nvim_set_hl(0, "NoiceMini", { bg = "#2f4159" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#81b29a" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#231911" })
vim.api.nvim_set_hl(0, "WhichKeyFloat", { bg = "#231911" })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "#91aed6" })
vim.api.nvim_set_hl(0, "@text.uri.html", { fg = "#ebd8b3" })
vim.api.nvim_set_hl(0, "@string.typescript", { fg = "#ebd8b3" })
vim.api.nvim_set_hl(0, "@string.astro", { fg = "#8db2a0" })
vim.api.nvim_set_hl(0, "@string.html", { fg = "#8db2a0" })
vim.api.nvim_set_hl(0, "@text.emphasis.html", { fg = "#d6d5cd" })
vim.api.nvim_set_hl(0, "@text.strong.html", { fg = "#d6d5cd" })
vim.api.nvim_set_hl(0, "@text.title.1.html", { fg = "#d6d5cd" })
vim.api.nvim_set_hl(0, "@text.title.2.astro", { fg = "#d6d5cd" })
vim.api.nvim_set_hl(0, "@text.title.html", { fg = "#d6d5cd" })
vim.api.nvim_set_hl(0, "@tag.html", { fg = "#91aed6" })
vim.api.nvim_set_hl(0, "@tag.astro", { fg = "#91aed6" })
vim.api.nvim_set_hl(0, "@type.typescript", { fg = "#91aed6" })
vim.api.nvim_set_hl(0, "@tag.attribute.html", { fg = "#daacd1" })
vim.api.nvim_set_hl(0, "@tag.attribute.astro", { fg = "#daacd1" })
